### ISSUE TITLE
Implement a color picker

### ISSUE THREAD

**Issue by MewPurPur** [MewPurPur/GodSVG#134]
There's no color picker currently, just some preset colors. I'm not sure about implementation details right now, but a color picker is needed, alongside the implementation of swatches. I'm not sure right now how this would look.

**Comment by Swarkin** [comment]
Why not use the built-in one?
[ColorPickerButton](https://docs.godotengine.org/en/stable/classes/class_colorpickerbutton.html) / [ColorPicker](https://docs.godotengine.org/en/stable/classes/class_colorpicker.html#class-colorpicker)

**Comment by MewPurPur** [comment]
Will probably be a part of the solution, especially the color wheel. The rest seems just not configurable enough.
