### ISSUE TITLE
Wrong highlighting when SVG ends in two newlines

### ISSUE THREAD

**Issue by MewPurPur** [MewPurPur/GodSVG#168]
Seems to be an upstream bug in Godot.  EDIT: Yes. https://github.com/godotengine/godot/issues/84381

**Comment by MewPurPur** [comment]
PR to look out for: https://github.com/godotengine/godot/pull/83543

If it's merged into Godot, the issue will be fixed automatically when the project moves to the version of Godot with it.

**Comment by SeremTitus** [comment]
@MewPurPur, you could use strip_edges()  on the String svg text before parsing

**Comment by MewPurPur** [comment]
Partially addressed by #375. Now the bug only materializes itself in the scenario as a bit of wrong syntax highlighting.
![image](https://github.com/MewPurPur/GodSVG/assets/85438892/2c139ad8-f692-48d0-945f-5554f1cbc2c9)
