### ISSUE TITLE
Elliptical arcs in `path` usually crash GodSVG

### ISSUE THREAD

**Issue by MewPurPur** [MewPurPur/GodSVG#17]
Steps to reproduce:

1. Make a path
2. Add a "MoveTo" command (`M`)
3. Tweak the MoveTo command to be something other than (0, 0)
4. Add an EllipticalArc command (`A`)

This freezes GodSVG for me on Ubuntu 22, Godot v4.1 rc1, and Godot is not leaving any trace. I have tried to patch it, but couldn't.

**Comment by ajreckof** [comment]
Okay so first this might be a ThorVG/Godot bug so we should most likely report it.
Secondly you should remove the A command in path as it is not supported by the tiny 1.2 specification.
