### ISSUE TITLE
Change renderer to "Compatibility"

### ISSUE THREAD

**Issue by thiagola92** [MewPurPur/GodSVG#181]
I don't think that GodSVG needs that much rendering, so I'm suggesting change "Forward+" to "Compatibility".  

![image](https://github.com/MewPurPur/GodSVG/assets/9352894/d83fde9b-69f9-4713-8b4f-e43043c59b49)

**Comment by MewPurPur** [comment]
I don't know much about renderers. What benefits will this bring?

**Comment by MewPurPur** [comment]
After some research, Compatibility seems like the way to go.

**Comment by thiagola92** [comment]
Sorry, I don't know about renderers too.  
I just felt a big performance cost when moving the window or moving images and suggested this.  

The final SVG/PNG wouldn't be affect.  
Would only affect the application while running.

**Comment by MewPurPur** [comment]
I'm getting weird results from the profiler, so I'd appreciate profiling to find what really is causing the performance problems. In any case, it's probably not because of the renderer, but Compatibility will still help by allowing GodSVG to run on old devices.
