### ISSUE TITLE
Clicking on svg element crashes the program

### ISSUE THREAD

**Issue by MarcusElg** [MewPurPur/GodSVG#205]
Gives the following error:

![image](https://github.com/MewPurPur/GodSVG/assets/19669673/a3cb263c-6e47-4548-8849-db409059a61b)

When clicking on the element:
![image](https://github.com/MewPurPur/GodSVG/assets/19669673/8436e1df-53c0-4a6e-beb1-12eb555b8888)

**Comment by MewPurPur** [comment]
Thanks for the report! Just fixed it.
