### ISSUE TITLE
Add a project license

### ISSUE THREAD

**Issue by Calinou** [MewPurPur/GodSVG#26]
The repository currently doesn't seem to contain any license. Could you add one, please? See [Choose a License](https://choosealicense.com/) for more information :slightly_smiling_face:

**Comment by MewPurPur** [comment]
I don't know law, but I assume it should be MIT?

**Comment by Calinou** [comment]
> I don't know law, but I assume it should be MIT?

If there are no other contributors, you can pick any license you want, but I'd recommend MIT :slightly_smiling_face:

**Comment by MewPurPur** [comment]
Alrighty, adding MIT then. Got permissions from everyone.

**Comment by MewPurPur** [comment]
Wait, this was already listed in the README. I guess I need to add a file, then.
