### ISSUE TITLE
Invalid get index 'window_mode' (on base: 'null instance') error

### ISSUE THREAD

**Issue by jsonify** [MewPurPur/GodSVG#28]
I just cloned, imported it from the Project List and opened the project. Then without making any changes, I get this error:

`Invalid get index 'window_mode' (on base: 'null instance')` and its stopping in the "_enter_tree()" at like 45.

I want to try to use this, but I'm stuck here.

**Comment by MewPurPur** [comment]
This is an early development software without a stable version yet. Currently the codebase is in a pretty messy half-finished state, but it's my top priority to clean it up and untangle the mess.

**Comment by jsonify** [comment]
Is there anything you’d like help with? I could try and help in any way I
can.

**Comment by MewPurPur** [comment]
OK Figured it out, it's not part of the stuff I'm refactoring.

**Comment by MewPurPur** [comment]
Fixed by https://github.com/MewPurPur/GodSVG/commit/b22b8c566063abe9c75afbe7bf7d30d91ea21459
