### ISSUE TITLE
Some `godot` tags

### ISSUE THREAD

**Issue by abitrolly** [MewPurPur/GodSVG#287]
Hi @MewPurPur. Adding `godot` tag to repo description would help discoverability https://github.com/topics/godot

**Comment by abitrolly** [comment]
These are actually called "topics". You need to click this button to add them.

![image](https://github.com/MewPurPur/GodSVG/assets/8781107/04253609-447d-488b-947b-574539fc856d)

**Comment by MewPurPur** [comment]
Doned.
