### ISSUE TITLE
Add CLI file opening and the ability to use "Open With"

### ISSUE THREAD

**Issue by ilikefrogs101** [MewPurPur/GodSVG#302]
it would be much faster to open files if you could do it from the command line or through many file managers open with function

**Comment by ilikefrogs101** [comment]
#303

made a PR with the tiny amount of changes that need to happen for it to work

**Comment by MewPurPur** [comment]
I don't understand this use case, could you explain it so I can understand it better?

**Comment by ilikefrogs101** [comment]
so, basically i can open up a terminal and run
GodSVG.x86_64 and it opens it but with the few lines I added i can also run GodSVG.x86_64 /path/to/svg/file and it will immediatly open up the svg you provide the path to. Ive done some experiments 6 months or so ago and I figured out this also enables file managers to use your program as the default for opening X file type, in your case svg. It saves the hassle of having to open the app, go to import and find you file. you can just directly open your app with the file there by default

**Comment by ilikefrogs101** [comment]
my git imploded and started causing errors on things i haven't touched so i will just redo it tomorrow

**Comment by ilikefrogs101** [comment]
#305 
Here we go, this should work
