### ISSUE TITLE
Better touch device support

### ISSUE THREAD

**Issue by Swarkin** [MewPurPur/GodSVG#312]
> Describe the limitation you're facing and how the feature will help resolve it. If you can, give more detail about the implementation.

The touch support is currently not good for devices with a small screen, like phones or even some tablets, as your input isn't as exact as you have it on a mouse.

A few examples:
- Trying to move elements via the handles is very difficult as their "hitbox" is way too small
- Many UI buttons are difficult to press
- Opening the keyboard overlaps the view box and makes svg direct code editing difficult to use

This list is by far not exhaustive.

This proposal doesn't have any urgency as of now but would be very nice to be done before Godsvg fully releases.

**Comment by MewPurPur** [comment]
1-2 look like they could be done with theme scaling, which is one of the high priorities at the moment.
