### ISSUE TITLE
Disable the "Warp mouse" setting, if it is not available.

### ISSUE THREAD

**Issue by MewPurPur** [MewPurPur/GodSVG#345]
`Control.warp_mouse()` is not always available, for example Web doesn't allow it, and Wayland doesn't support it yet AFAIK (I haven't tested this). So on these platforms, the setting should be disabled and maybe some kind of warning should be given.

**Comment by Vovkiv** [comment]
So, I looked in docs and found that:
"Note: warp_mouse() is only supported on Windows, macOS and Linux. It has no effect on Android, iOS and Web." So, effectively you can move mouse only on Linux X11, MacOS and Windows, everywhere else you can't due to better security

**Comment by MewPurPur** [comment]
I think the Wayland scenario should be reported as an upstream bug here, and we should follow what the documentation claims.

**Comment by Vovkiv** [comment]
> I think the Wayland scenario could be reported as an upstream bug here, other than that, we should follow what the documentation claims.

It's not a bug, it's feature (TM)
I think easiest and best way to do, is to just make big red label: "THIS FEATURE MIGHT NOT WORK ON YOUR SYSTEM"

**Comment by Vovkiv** [comment]
> That's not the case here IMO. The security argument doesn't hold that well and there's already discussion on improving the situation as linked, it's just that not many people are interested in working on it, from what I can see, as the `pointer-constraints-v1` already has partial support for this feature, albeit a bit shortsighted.
Honeslty, I like to think of this as security feature (even if it isn't). I kind of enjoy when programs is not being able to manipulate my cursor whenever they feel like it, particularly games. (For example, Elder Ring has bad habit of blocking cursor inside it's own window, preventing me from moving cursor to second monitor)
