### ISSUE TITLE
viewBox 0 values

### ISSUE THREAD

**Issue by Alex2782** [MewPurPur/GodSVG#358]
v4.2.1.stable.official [b09f793f5]

I updated my branch today, 176 new commits.

Is the problem already known? I first had this error on my MacOS, restarted Godot Editor several times and the app, created a few SVG nodes (not visible, as in the screenshot) and closed the app.

Now the error is also on my Samsung Tab S7. 

```
12-28 21:12:06.649 16011 16052 E godot   : USER ERROR: Condition "!isfinite(p_size.x) || !isfinite(p_size.y)" is true.
12-28 21:12:06.649 16011 16052 E godot   :    at: set_size (scene/gui/control.cpp:1448)
12-28 21:12:06.661 16011 16052 E godot   : USER ERROR: Condition "p_points.is_empty() || p_points.size() % 2 != 0" is true.
12-28 21:12:06.661 16011 16052 E godot   :    at: canvas_item_add_multiline (servers/rendering/renderer_canvas_cull.cpp:1084)

```

![Bildschirmfoto 2023-12-28 um 21 12 56](https://github.com/MewPurPur/GodSVG/assets/41921395/90d581f4-e301-43aa-b9bf-7fef881084f6)

**Comment by MewPurPur** [comment]
Thanks for the report, yes, a lot of wrongness is going on in this image. How can this be reproduced?

**Comment by Alex2782** [comment]
maybe user settings

![image](https://github.com/MewPurPur/GodSVG/assets/41921395/04cd73ba-ad5c-47fb-8d5a-22cf2d096fac)

**Comment by Alex2782** [comment]
I don't yet know exactly how to reproduce it, but it worked again on the MacOS after 5 minutes (not on my Android Tablet). But when I try to adjust the size, another error appears. My guess is that old settings are no longer compatible.

example: change **height** from 16 to 32, crash in editor

![Bildschirmfoto 2023-12-29 um 01 55 25](https://github.com/MewPurPur/GodSVG/assets/41921395/1d969c82-058c-43d2-9a47-5e35f4db6143)

![Bildschirmfoto 2023-12-29 um 01 56 15](https://github.com/MewPurPur/GodSVG/assets/41921395/58380a2d-43c9-417c-81e8-a0da3907ce5f)

**Comment by Alex2782** [comment]
I tried the bugfix, no changes on my Samsung tablet. Uninstalling the app doesn't help either, do you know where Godot saves the user settings on Android?

**Comment by MewPurPur** [comment]
Can you get to this state after typing in any of width and height/viewBox manually in the code editor top left?

**Comment by Alex2782** [comment]
- test with 32 x 32 (screen)
- when I restart the app, the entries are reset to 0.5 x 0.5, or the settings are not saved correctly

![Bildschirmfoto 2024-01-05 um 17 46 42](https://github.com/MewPurPur/GodSVG/assets/41921395/3267e423-6007-47fd-bf28-eb9acde64985)

**Comment by Alex2782** [comment]
`print("user settings: ", ProjectSettings.globalize_path("user://"))
`
**output**
`user settings: /data/data/com.example.godsvg/files/`

**Comment by MewPurPur** [comment]
Hmm, okay, something in the export settings is wrong. Would appreciate help here.

**Comment by Alex2782** [comment]
[Archiv.zip](https://github.com/MewPurPur/GodSVG/files/13844720/Archiv.zip)

![image](https://github.com/MewPurPur/GodSVG/assets/41921395/687a12e3-f2b6-448d-927b-d582593b66ba)

**Comment by Alex2782** [comment]
I'll try to debug it next week, at first I had it under MacOS as well.

**Comment by Alex2782** [comment]
now ok on Android,  I have manually entered `width="16"` there


![Bildschirmfoto 2024-01-05 um 20 31 20](https://github.com/MewPurPur/GodSVG/assets/41921395/01d2cc56-af0e-4e9f-a277-485f356ee919)

**Comment by Alex2782** [comment]
1. `print("user settings: ", ProjectSettings.globalize_path("user://"))`
2. delete `save.tres`
3. now also on my MacOS again
![image](https://github.com/MewPurPur/GodSVG/assets/41921395/df039624-7fae-47a3-bdad-25a66ac5b84c)

**Comment by Kiisu-Master** [comment]
I can reproduce this by making the svg string empty in the save.
Also happens when deleting save.

**Comment by Kiisu-Master** [comment]
If i disable the other conditions and only run this, it will always start blank.
I believe this code does not work.
https://github.com/MewPurPur/GodSVG/blob/952bf22f2d53c4374c59229b3575ed4832597280/src/SVG.gd#L37C1-L40

**Comment by Kiisu-Master** [comment]
Sync mode loud should be ok to use as we clear undo redo right after, but intermediate works too.

**Comment by MewPurPur** [comment]
What do you mean by toggles?

**Comment by Kiisu-Master** [comment]
The root tag editor where you edit width and height of SVG.
Everything is disabled by default but there is width and height inside the SVG code.
![image](https://github.com/MewPurPur/GodSVG/assets/142301391/c4db25e5-9d7a-457c-b792-88de9386b147)
