### ISSUE TITLE
100% zoom should be exactly enough to fit the svg on screen independently from it's size

### ISSUE THREAD

**Issue by Swarkin** [MewPurPur/GodSVG#36]
This is so that you don't have to zoom in or out very far depending on the svg size, and that the percentage display between the zoom buttons indicates how far its been zoomed relatively to its size.

A possible way of doing this would be to look at the specified viewBox (I believe this is how its called) inside the svg and work with that.

**Comment by MewPurPur** [comment]
That would be nice. Not "exactly" though, there should be some leeway to see handles outside of the screen when I implement them for paths.
