### ISSUE TITLE
Add an option to display a reference image behind the SVG

### ISSUE THREAD

**Issue by KittyMcTophat** [MewPurPur/GodSVG#376]
**Limitation**
I want to recreate a png image in svg format, but I want to trace over the original to get it right. Currently, I can't do that since it's not a feature.

**How It Will Help**
By adding the option for displaying a reference image, it will become much easier to recreate images in svg format, because they can be traced.

**Implementation Details**
My proposal is to add an option to load a reference image, which would be rendered behind the svg image at 50% transparency or something like that, allowing a much easier way to recreate raster images in svg format.

It would also be helpful if there were a button or a hotkey to toggle the visibility of the reference image, since that'd make it easy to quickly tell which parts of the image aren't done yet at a glance.

**Comment by Kiisu-Master** [comment]
Should also add option for plain color
I had this idea a while ago but never talked about it 🙃

**Comment by MewPurPur** [comment]
Some implementation details would help me a lot.

**Comment by vthilag** [comment]
> Some ideas for implementation details would help me a lot to approach this.

Funnily enough, I wanted to vectorize a rasterized logo in godsvg and found this.
My idea would be a menu near the settings icon on top of the visual editor which has a sub menu called image reference that has the following options:
1. Select Image
2. Is Visible
3. Overlay Image or Display behind
4. Opacity
5. Lock transform
(Some of these can and probably should be separate items outside the menu for quick access)

When not locked you'd be able to click and transform the reference image and when it locks it'll no longer be selectable.

That's how I'd probably use it but they're definitely better ways.

**Comment by MewPurPur** [comment]
Thanks! This will help me (or others) get started.

**Comment by Qainguin** [comment]
This should be implemented now by #728.

**Comment by MewPurPur** [comment]
Yeah. More advanced requirements can be discussed separately and implemented when the need for them becomes a priority.
