### ISSUE TITLE
Out of bounds error when using a path shortcut after undo

### ISSUE THREAD

**Issue by DevPoodle** [MewPurPur/GodSVG#454]
On a path tag that already has some points on it:
- Create a new point
- Undo that point using Ctrl-Z
- Create a new point using a keyboard shortcut such as "M" or "L"
- You should get an out of bounds error in AttributePath

**Comment by MewPurPur** [comment]
I'm not managing to reproduce it in main, can you post a video?

**Comment by MewPurPur** [comment]
I reproduced it now
