### ISSUE TITLE
Ability to rotate or scale the path

### ISSUE THREAD

**Issue by tokengamedev** [MewPurPur/GodSVG#482]
When I wanted to edit a SVG (e.g., arrow) and to rotate or scale, I am unable to do it as I am not sure how to do it.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
    <path d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z"/>
</svg>
```

**Suggested Idea:**
Include modes for Edit operations like
- Edit (Normal edit mode, draw and others)
- Move (Move the path or other objects inside the view box)
- Scale (Scale the path inside the view box)
- Rotate (Rotate the path inside view box)

Note: This may be possible today, but I could not figure out. It will be intuitive for the end user to edit in modes.

**Comment by MewPurPur** [comment]
> Note: This may be possible today, but I could not figure out. It will be intuitive for the end user to edit in modes.

It's not possible in alpha 2, but it's already possible in master.

**Comment by MewPurPur** [comment]
Already solved by #394, will be in a stable release soon. Thanks for the feedback!

**Comment by Kiisu-Master** [comment]
I do like the idea of adding different editing modes.
Would maybe help solving having to display everything at once in the inspector. Also a more standard way of how applications work.

**Comment by MewPurPur** [comment]
The code editor should display everything at once always, I don't think I'll change this - although I'm not opposed to being able to focus on specific elements and their hierarchies.

As for tag editors, I think we need to first try to have them be a bit a little bit more specific to their tag. For example, I plan to hide stroke-related things until you have a stroke that's not set to "none". That should help with the clutter.

**Comment by tokengamedev** [comment]
I tested this after cloning from master. did you merge yesterday or something. I am not sure how to do it. 
Will it use transform attribute or apply the transformation into coordinates.

**Comment by MewPurPur** [comment]
It uses a transform attribute, and eventually I want to make it so transformations can be incorporated into the shapes.
