### ISSUE TITLE
Issues with SVG rendering

### ISSUE THREAD

**Issue by ajreckof** [MewPurPur/GodSVG#5]
resizing the view cause the shape to move most likely because of imprecision
https://github.com/MewPurPur/GodSVG/assets/66184050/2744d236-db28-4b6d-bd9a-64daae52c60e

**Comment by MewPurPur** [comment]
SVG rendering is pathologically broken. I'm generating an oversized image (which is very expensive, by the way) and using it. This is good and not too slow for 16x16, but starts becoming pixelated if I try to make it look OK at higher values.

No idea how to solve this, but it's one of the most important issues to resolve.

**Comment by ajreckof** [comment]
I'll take a look to see if i can do anything about it
