### ISSUE TITLE
Give GodSVG a better icon

### ISSUE THREAD

**Issue by MewPurPur** [MewPurPur/GodSVG#51]
Self-explanatory, GodSVG needs a good app icon. I'm thinking of keeping the blue flame, maybe even having some subtle reminiscence of Godot in its overall shape. I don't think the handle is necessary, or the eyes. The eyes are cute though, I'll try to keep them when/if I wind up making the design!

**Comment by MewPurPur** [comment]
I'll make some sketches tomorrow.

**Comment by MewPurPur** [comment]
![GodSVG sketch 2](https://github.com/MewPurPur/GodSVG/assets/85438892/96c3b0eb-e1e7-4e9d-8d33-0c4f4f4fee51)

Now I'm onto this cute fox making a paint stroke with its tail, in an overall G shape.

**Comment by MewPurPur** [comment]
Pinning as solving this is for the first alpha would be great.

**Comment by Volts-s** [comment]
Hi, I whipped this up in Affinity Designer.   The SVG is as exported by Affinity.  
![GodSVG_Icon](https://github.com/MewPurPur/GodSVG/assets/28009043/5957d60b-ce3f-4593-a666-d494776aeabe)
![GodSVG_Icon](https://github.com/MewPurPur/GodSVG/assets/28009043/2cfce59b-5ff9-4b85-91cf-3a8a767f1d38)
![GodSVG_Logo](https://github.com/MewPurPur/GodSVG/assets/28009043/923165ad-3033-4e6e-a407-5d1f779a2b2a)

**Comment by MewPurPur** [comment]
![Clipboard - November 9, 2023 9 26 PM](https://github.com/MewPurPur/GodSVG/assets/85438892/a898d6fd-22f6-489d-b804-257730798952)

This was my sketch over the above drawing.

**Comment by MewPurPur** [comment]
> Hi, I whipped this up in Affinity Designer. The SVG is as exported by Affinity. ![GodSVG_Icon](https://user-images.githubusercontent.com/28009043/284372427-5957d60b-ce3f-4593-a666-d494776aeabe.jpg) ![GodSVG_Icon](https://user-images.githubusercontent.com/28009043/284372432-2cfce59b-5ff9-4b85-91cf-3a8a767f1d38.png) ![GodSVG_Logo](https://user-images.githubusercontent.com/28009043/284372434-923165ad-3033-4e6e-a407-5d1f779a2b2a.svg)

I love this, but it strays off a little from what I was aiming for with the fox icon:

- I'm pretty set on using blue as the main color at this point, and I'm also set on having a simple icon without tiny details, one that would have its details easy to discern even at a resolution like 16x16. So I prefer not to go with a rainbow.
- This logo is C-shaped, while the overall shape of the fox with its paint trail in the concept is G-shaped. This is important to the concept as it's the first letter of the app.
- The face expression is reminiscing of Anonymous masks - I prefer not to have any mouth (as explained above, no small details). I only want to have a closed eye with of a happy face (as the above post), or a sleepy face (like the pic below) because while it's a tiny detail, it does a lot to emphasize the cuteness of the logo.

![image](https://github.com/MewPurPur/GodSVG/assets/85438892/6f3e68f3-680d-4c6f-a86e-dd6b120709b5)

**Comment by Volts-s** [comment]
I think I get what you are aiming for.  I'll take another shot at this.  This is a cool and ambitious project.

**Comment by MewPurPur** [comment]
Thanks a lot for the effort!

**Comment by MewPurPur** [comment]
P.P.S. Sorry nevermind, it's easy to fetch the text when you post a SVG file on Github, so it doesn't matter.

**Comment by Volts-s** [comment]
I worked up some new variants based on your sketches and rendered them at powers of 2 from 128 to 16 px square.  Let me know what you think.   I will provide the SVG (and Affinity files, if you want them) when we settle on a design.  Also, I can fix the faint line across the dark blue in the middle color scheme.
--
128 px
[
![Blues128](https://github.com/MewPurPur/GodSVG/assets/28009043/4f048f9f-7d21-4577-995c-9177f25d3015)   ![Colors128](https://github.com/MewPurPur/GodSVG/assets/28009043/00be7738-8dbf-4f66-9ea5-185d60d14947)   ![Hybrid128](https://github.com/MewPurPur/GodSVG/assets/28009043/1868ce2b-b60f-464d-9772-f980217ae1b1)
](url)
--
64 px
![Blues64](https://github.com/MewPurPur/GodSVG/assets/28009043/7ee7c863-66a1-45d5-8778-3a3bb189a333)   ![Colors64](https://github.com/MewPurPur/GodSVG/assets/28009043/ca3649a8-92ac-4cf1-95c4-9f678678f9b2)   ![Hybrid64](https://github.com/MewPurPur/GodSVG/assets/28009043/aae12d01-3363-4757-a84a-b693bc3907ce)
--
32px
![Blues32](https://github.com/MewPurPur/GodSVG/assets/28009043/6e1b39d5-e919-4593-908f-0ca8f6f41c6c)   ![Colors32](https://github.com/MewPurPur/GodSVG/assets/28009043/5c5dc2f9-8630-420a-b1c8-ca3b6d31a540)   ![Hybrid32](https://github.com/MewPurPur/GodSVG/assets/28009043/1a7dc9d3-1e77-4272-87c8-27bb4b6815a1)
--
16px
![Blues16](https://github.com/MewPurPur/GodSVG/assets/28009043/b80e8268-9b5f-4c9e-8df1-e34e790b1b0b)   ![Colors16](https://github.com/MewPurPur/GodSVG/assets/28009043/4e771845-dd7c-4591-ae05-e678ee613a95)   ![Hybrid16](https://github.com/MewPurPur/GodSVG/assets/28009043/74a9186c-b348-47b6-ac84-3b328dffde69)

**Comment by MewPurPur** [comment]
I like this! I don't really have much to critique. The main thing is, I'd like to see whether a version without outlines could work.

Don't worry about artifacts as long as the overall shapes are right, since in the end I'll tweak slightly the shape, colors, etc. and optimize it anyway.

Minor remarks:

- The orange sploch above the paint trail must go, the ones at the end shouldn't be different colors.
- The paint trail should be smoother
- It should be clearer that the fox's cheek tuff is not part of the face.
- the end of the tail is sticking too far to the right

**Comment by Volts-s** [comment]
Here is the next iteration - with and without outlines. Personally I prefer no outlines.

128px
--
![Hybrid128](https://github.com/MewPurPur/GodSVG/assets/28009043/2d1a1d41-ab5a-44d4-9ee3-825727c51e4f)   ![Hybrid solid128](https://github.com/MewPurPur/GodSVG/assets/28009043/167da10a-01f4-4a03-ae72-29fa5bd9d7b2)   

64px
--
![Hybrid64](https://github.com/MewPurPur/GodSVG/assets/28009043/3cb7258a-b4ee-4e0b-a1dd-d0eea26258e9)   ![Hybrid solid64](https://github.com/MewPurPur/GodSVG/assets/28009043/03de8540-0a50-4738-8a82-42183872b62d)   

32px
--
![Hybrid32](https://github.com/MewPurPur/GodSVG/assets/28009043/7ca439e5-7a2f-4a70-8360-3eb72df376bc)   ![Hybrid solid32](https://github.com/MewPurPur/GodSVG/assets/28009043/d9457e11-33d0-43a8-8757-fa571b298851)   

16px
--
![Hybrid16](https://github.com/MewPurPur/GodSVG/assets/28009043/3e8266d9-b5b0-468e-9557-552e52681838)   ![Hybrid solid16](https://github.com/MewPurPur/GodSVG/assets/28009043/6ade4f4f-f361-4b2a-aa64-24747e8a07a5)

**Comment by MewPurPur** [comment]
Cool! Can I get an SVG of the last no-outline version? Also, what's your real name? (Or do you want to be credited only by your Github handle?)

**Comment by Volts-s** [comment]
Hi, Here is the SVG.  My name is Tom Blackwell.
--
![GodSVG Icon](https://github.com/MewPurPur/GodSVG/assets/28009043/26c64269-b972-4a18-8a7f-5468d69dc302)

**Comment by Volts-s** [comment]
Also, here is a version with the outline of the red part of the stroke improved a little. 
--
![GodSVG Icon Improved](https://github.com/MewPurPur/GodSVG/assets/28009043/08b199fd-eb94-4f2d-a8e6-7eef705cad45)

**Comment by Volts-s** [comment]
You're welcome. 🙂

**Comment by MewPurPur** [comment]
Closed by #243
