### ISSUE TITLE
File dialog is broken in the web build

### ISSUE THREAD

**Issue by Pacomatic1** [MewPurPur/GodSVG#511]
Let's say I'm using the web build, and I want to import or export something.
I get this:
![image](https://github.com/MewPurPur/GodSVG/assets/74610266/066bf0b9-239f-4d8b-ac33-b1e029da9bc7)
At first glance, this seems fine, but it's actually not; because this is not any part of my PC.
I faintly recall the Godot docs saying something about web builds accessing a database with a filesystem inside; maybe that's what it's looking through?

Either way, I think the problem is that it opens Godot's file manager, when we really want the OS file manager.

**Comment by Pacomatic1** [comment]
I can tell this dialog uses the FileDialog node, so maybe try this:
[https://docs.godotengine.org/en/stable/classes/class_filedialog.html#class-filedialog-property-use-native-dialog](url)
No idea if it works on Web, and I'm having issues trying to clone the repo + I haven't exported to web yet.
But I'll try.

**Comment by MewPurPur** [comment]
I'm not sure how to fix this right now, but for a starting point, let's go over how it's implemented. GodSVG checks if the DisplayServer supports native file dialogs. If it does, it instantiates one. If it does not, it uses this fake wonky FileDialog scene as a fallback.

Not sure what a solution would look like, but it should be possible.

**Comment by Pacomatic1** [comment]
I'm currently unable to compile to web, but I have an idea:

According to the docs, you can use a custom HTML page to have custom JavaScript functions, which are callable by the game.

So maybe we could use a custom web page, add a function that opens the OS file manager for FileDialogs, and then make GodSVG use it if you're on web.
