### ISSUE TITLE
is there build instructions 

### ISSUE THREAD

**Issue by MissLavender-LQ** [MewPurPur/GodSVG#527]
what version of godot do i need to be on to make the latest version of GodotSVG 
i tried loading the project in latest and it wouldn't load correctly 
just wondering if there is build instructions somewhere or if there is gonna be a new build soon 

https://github.com/MewPurPur/GodSVG/assets/51702517/643ed41d-fd29-4de0-9cee-6ca75157113e

**Comment by MissLavender-LQ** [comment]
ah heard thanks u! 
after that do i just do export 

> The version you're using is correct. (Godot would tell you if it weren't) It's currently in 4.2, but might have problems when first opening. You need to reload the project at least once after first time opening. This is a godot problem and isn't specific to GodSVG.

**Comment by Kiisu-Master** [comment]
Yes, if you want a standalone executable. But you can also use it by launching from the editor (or project manager, if you have launched it from editor already).

**Comment by MissLavender-LQ** [comment]
is there any way to change the ui scale this feels pretty cramped on desktop 
![image](https://github.com/MewPurPur/GodSVG/assets/51702517/ca237fa4-25c3-4113-9d61-11ccc6ebdf46)

**Comment by MissLavender-LQ** [comment]
also icons look blury 
![image](https://github.com/MewPurPur/GodSVG/assets/51702517/0555e900-d0d4-4b85-82e4-847c64c771fb)

**Comment by Kiisu-Master** [comment]
You need to reset the window stretch mode settings in project settings. Godot has some limitations when scaling ui.

![image](https://github.com/MewPurPur/GodSVG/assets/142301391/38bf6253-680a-4a85-9a76-61253f627873)

**Comment by MissLavender-LQ** [comment]
thank u ❤️
