### ISSUE TITLE
Allow asymmetric length for shorthand beziers

### ISSUE THREAD

**Issue by addmix** [MewPurPur/GodSVG#530]
Currently shorthand bezier handles are linked in both direction and length. Typically bezier handles, with symmetry enabled, allows for independent scaling of opposing handles.

**Comment by MewPurPur** [comment]
Unlike other editors, GodSVG is just a middleman between the actual SVG code and you, so it can't behave like them here. Shorthand beziers in SVG are implemented by omitting an entire handle, so changing this isn't an option.

Something actionable here would be to add a keybind, like Shift, to force a bezier control handle to align with the previous one.

**Comment by MewPurPur** [comment]
Closing as #531 documents this class of issues.
