### ISSUE TITLE
High GPU usage on idle

### ISSUE THREAD

**Issue by Kiisu-Master** [MewPurPur/GodSVG#537]
I noticed it when running the project with forward+ instead of compatibility, but i think it's doing the same on compatibility.

I think Godot is capable of preventing continuously redrawing, as the editor itself has a spinner to debug the editor redrawing, and there is a canvas item redraw debug visualisation available for debugging projects . When turning it on, it doesn't show anything updating on idle so i have no clue what's causing the GPU usage to go to 80%  :/

**Comment by MewPurPur** [comment]
I've taken a lot of care to avoid unnecessary redraws, so I don't know what's up with that either.

Is there any way to monitor this so I can know when it's fixed?

**Comment by Kiisu-Master** [comment]
I noticed it when my laptop got hot and i looked in the GPU usage in the task manager.
I don't remember seeing a GPU tab on linux task managers, but im sure theres a way to monitor it.

**Comment by MewPurPur** [comment]
Didn't find any way to measure this, so I can't do anything.

**Comment by Kiisu-Master** [comment]
Maybe this https://github.com/Syllo/nvtop
