### ISSUE TITLE
Implement Undo and Redo

### ISSUE THREAD

**Issue by MewPurPur** [MewPurPur/GodSVG#55]
Use Godot's UndoRedo to make actions reversible. Add `Ctrl+Z` as a shortcut; for Redo, allow both `Ctrl+Y` and `Ctrl+Shift+Z`. For an initial implementation, the whole SVG's state can be saved after each action, rebuilding all global definitions and tag editors in the process.

Interestingly, the code editor's own UndoRedo already works quite decently. But it considers every adjustment as an action, even if you're just holding a spinner arrow or dragging a handle.

**Comment by MewPurPur** [comment]
Not working on this _right_ now, turned out to be a tougher nut to crack than I hoped.

**Comment by SeremTitus** [comment]
#104

**Comment by MewPurPur** [comment]
Pinning as solving this important for the first alpha.
