### ISSUE TITLE
Add way to create and modify groups through UI

### ISSUE THREAD

**Issue by ajreckof** [MewPurPur/GodSVG#581]
Group tag are already present in the application as they are understood if added from the code editor they will appear normaly but they have huge limitations. 
1. You can't create a tag directly inside you need to add the tag and then move it inside
2. Group parameters that applies on all element inside are editable but as they are not recognised they all default to string instead of having editor adapted to the value 
3. You can't add new group parameter
4.  Handles for element inside groups are not shown.

**Comment by MewPurPur** [comment]
Duplicate of https://github.com/MewPurPur/GodSVG/issues/434

**Comment by ajreckof** [comment]
Sorry searched for group but didn't think of searching for the tag itself.
