### ISSUE TITLE
Gradient stops not working correctly if the gradient is used as path stroke color

### ISSUE THREAD

**Issue by RedFurryDemon** [MewPurPur/GodSVG#646]
Bug occurs inconsistently. Further testing needed.

**Expected behavior:**

Like gradients used for any fill colors or stroke colors of shapes other than path, gradients used as path stroke colors should update both in the preview window and in the SVG text editor immediately after any of their stop properties are changed.

**Current behavior:**

Gradients used as path stroke colors may fail to update in the preview window until the preview is zoomed in/out. They may also fail to update _at all_ in the SVG text editor. These problems seem to occur together.

**Sample file:**
![gradient_stroke_sample](https://github.com/MewPurPur/GodSVG/assets/55105171/cfe2e295-3dbc-47de-984b-b72ccf6f8503)

**(Steps to reproduce):**
Using GodSVG UI, edit any of the stop properties of `g_stroke`. The bug may or may not appear.

**Comment by MewPurPur** [comment]
could you post the SVG text itself?

**Comment by RedFurryDemon** [comment]
When this occurs, the SVG text before and after editing the stops is identical.

I uploaded the file in the bug report - `open in new tab`, `view page source` to see the SVG text.

**Comment by MewPurPur** [comment]
Can't reproduce. A video would help to see how you're getting it to happen.

**Comment by MewPurPur** [comment]
I tested more, I still can't reproduce.
