### ISSUE TITLE
Strings in context menus can go outside of button if they very long

### ISSUE THREAD

**Issue by Vovkiv** [MewPurPur/GodSVG#670]
If line gets very long in context menus (in this case, menu for converting tags), it will be wrapped in way that it can go outside of button boundaries, so text might get overlapped:
![зображення](https://github.com/MewPurPur/GodSVG/assets/54743395/bec627ac-a678-4b78-97ca-aa2bfbdcb3a6)

**Comment by MewPurPur** [comment]
This shouldn't be a problem in context menus, but the path popup is a fixed width.

I think the correct solution would be to let the text shrink a little, and if it's still not enough, make the popup wider.

**Comment by MewPurPur** [comment]
Fixed by #741
