### ISSUE TITLE
Make commands more discoverable.

### ISSUE THREAD

**Issue by adambelis** [MewPurPur/GodSVG#680]
![image](https://github.com/MewPurPur/GodSVG/assets/50795097/41b45586-5878-45aa-a057-53dc35e29a46)

**Comment by MewPurPur** [comment]
You're right that this has poor discoverability. But tags can have up to 5 options, and I want to add a few more at some point. I think this only looks good for a tag with just 2-3 options. Having 5 icons listed there would feel quite busy, and also a bother as you can't see what does what without hovering and waiting for the tooltip.

Thanks a lot for the suggestion nonetheless! But I think the tag frame is better the way it is now.

**Comment by MewPurPur** [comment]
Kiisu suggested that we can make this only be shown on hover, and maybe, we could also tinker with instant tooltips. I think that's worth exploring.

**Comment by adambelis** [comment]
i woas thinking same  when i seen there are more buttons  for some  elements. Again if there si to many commands you can combine mosed use commands + hamburger
perosnaly i think reorder buttons are very redundant pattern dragg and dropping si faster and more legant solution (i know that this is implemented already.)

corventing could also maybe e done this way 
![image](https://github.com/MewPurPur/GodSVG/assets/50795097/69c5beb5-baf3-4f6d-8e2e-3a014817fab5)

**Comment by adambelis** [comment]
i see that renaming is not implmneted but again this could be done by just clcikong on name

**Comment by MewPurPur** [comment]
For things like gradient stops, moving up/down will be a useful operation. Also, they will serve a discoverability purpose when shortcuts are documented inside context popups (`Ctrl + Down/Up` is more efficient than drag-and-drop).

> i see that renaming is not implmneted but again this could be done by just clcikong on name

I don't plan to implement renaming in GodSVG. We're trying to be a good stateless editor for optimized graphics, so for now we just show the SVG as is, without directly supporting metadata that's unnecessary for rendering, like tag names.

**Comment by MewPurPur** [comment]
In my opinion, this is resolved by #763.
