### ISSUE TITLE
Web build exports an unknown file

### ISSUE THREAD

**Issue by Qainguin** [MewPurPur/GodSVG#682]
Whenever you export a file in the web build, it exports a file called "Unknown" for SVG and "png" for PNG without a file extension. Simply changing these files to add a .svg or .png seems to fix it but it still would be nice to be fixed.

**Comment by MewPurPur** [comment]
I can confirm this, although for SVGs I get a letter jumble rather than "Unknown".

**Comment by Qainguin** [comment]
Ah, I'm on MacOS so that might be why I'm getting Unknown.

**Comment by Kiisu-Master** [comment]
https://github.com/MewPurPur/GodSVG/blob/0b9030c8d354c084ec0c3f4aaeb115fa590c17b1/src/HandlerGUI.gd#L317-L323

**Comment by Qainguin** [comment]
Yeah, it does I'm working on a fix right now.
