### ISSUE TITLE
Importing SVG with no width, height, or viewport doesn't work

### ISSUE THREAD

**Issue by Qainguin** [MewPurPur/GodSVG#684]
If you import an SVG that is too big for GodSVG to handle, it will save that file path and try to load it. This makes the program forever unusable on the computer.

**Comment by MewPurPur** [comment]
Is this referring to big SVGs, or some non-svg file with an erroneous SVG extension? Also, is there a crash, eternal freeze, or will it load if you wait long enough?

If it's the last one, then my personal belief is that we shouldn't implement anything special for this case, we should just find more big optimizations to implement.

If there's a crash, we can use the crash handler notification - if there's a crash before READY is finished, then add a "program_crashed_last_time" sort of thing to the save data. On next launch, show a dialog asking if you want to try to load the SVG text and its path again, or start completely fresh.

**Comment by Qainguin** [comment]
I would suggest just adding a timeout for loading an SVG for now so that people can still use the software. This can be removed once optimization is good enough.

**Comment by Qainguin** [comment]
> Is this referring to big SVGs, or some non-svg file with an erroneous SVG extension? Also, is there a crash, eternal freeze, or will it load if you wait long enough?
> 
> If there's a crash, we can use the CRASH notification - if there's a crash before READY is finished, then add a "program_crashed_last_time" sort of thing to the save data. On next launch, show a dialog asking if you want to try to load the SVG text and its path again, or start completely fresh.
> 
> But if there's no actual crash, just an eternal freeze, the above is useless, so we're just back to optimizing.

Also, it is from Kenney assets, it is a regular SVG file with a .svg extension, and it will not load if I wait long enough.

**Comment by MewPurPur** [comment]
Could you post the SVG here by the way? I'd like to inspect if there are any outstanding issues for this particular one.

**Comment by Qainguin** [comment]
![kenny-vector-objects](https://github.com/MewPurPur/GodSVG/assets/94211064/2281eae1-36b1-4422-972b-a8ee5cd6b6e8)
It is a 365KB SVG file.

**Comment by MewPurPur** [comment]
Figured it a possible culprit. The SVG in question has neither width and height, nor a viewBox. Our editor breaks in multiple ways in this scenario, in fact, I kinda thought SVGs like these were just illegal. But it seems like we should instead implement this as some sort of "infinite canvas mode".

**Comment by MewPurPur** [comment]
I personally got this to open eventually, but like I said, the editor is broken and really slow.

![image](https://github.com/MewPurPur/GodSVG/assets/85438892/6ba1afe5-abe5-4159-b302-bcfece41f76a)

**Comment by Qainguin** [comment]
I changed the title to better reflect the issue.

**Comment by MewPurPur** [comment]
The occasional crash probably still had to do with the weight of our UI or other things, but yeah there is definitely a problem here too.

**Comment by Qainguin** [comment]
Another note with the vector_objects.svg file, now after a couple commits, it doesn't crash the editor and doesn't save it to the file path but it does do this.

<img width="1440" alt="Screenshot 2024-05-19 at 2 17 55 PM" src="https://github.com/MewPurPur/GodSVG/assets/94211064/11b740eb-a898-47e6-b1cc-83c6dfd42468">

**Comment by MewPurPur** [comment]
That's interesting. The logic around zero-size files should be refined, this is actually a necessary fix before alpha 4.

I think it no longer crashes because of some commits that improved Godot's memory usage.

**Comment by Qainguin** [comment]
Yeah, but how does it show no editor?

**Comment by MewPurPur** [comment]
Ow, I didn't understand the screenshot. I have no idea, but I'll for sure take on this bug this week. It's the 2nd highest priority right now.
