### ISSUE TITLE
d7 shows instead of a multiplication symbol in the export_dialog

### ISSUE THREAD

**Issue by Qainguin** [MewPurPur/GodSVG#685]
It shows a box with d7 inside of it instead of a multiplication symbol in the export_dialog. Only web is confirmed to have this issue. (cannot test natively currently)

<img width="302" alt="Screenshot 2024-04-26 at 11 21 54 AM" src="https://github.com/MewPurPur/GodSVG/assets/94211064/1d535bab-b36e-478b-b9f6-4e0e1bef53bf">

**Comment by MewPurPur** [comment]
I think this is because while peeking around the app in Godot, the fallback of the mono font - which doesn't have a multiplication system itself - was removed. This shouldn't exist in GodSVG's main branch.

In any case, we can use the normal font for the "Final size" label.

**Comment by Qainguin** [comment]
Alright, I'll try to add that.
