### ISSUE TITLE
Allow moving view with middlemouse while dragging a handle.

### ISSUE THREAD

**Issue by WeaverSong** [MewPurPur/GodSVG#713]
Just a minor thing, but currently you cannot move the view while dragging a handle; so if the place you want to put the handle is off the screen, you have to drop it, move the view, then drag it again.

**Comment by MewPurPur** [comment]
Can't seem to reproduce on my laptop's touchpad. Do you mean scrolling the mouse wheel, or something different?

**Comment by WeaverSong** [comment]
Not scrolling the mouse wheel, but using middlemouse + dragging to move the view. If you don't have a handle hovered both left click and middle click + drag will move the view, but when a handle is being dragged left click is in use, and middle click does nothing.

**Comment by MewPurPur** [comment]
OK, will try to squash this when I get my hands on a :mouse2:
