### ISSUE TITLE
Add right-click option to handles to scroll the tag list to view the tag with that handle

### ISSUE THREAD

**Issue by WeaverSong** [MewPurPur/GodSVG#714]
It's very easy to find a tag that needs to be edited visually, but inconvenient to find it in the tag list for when the handles are insufficient.

**Comment by MewPurPur** [comment]
I approve, but I'm unsure of the implementation. I was trying to do this at one point by trying to make it automatically scroll. It didn't work. Nowadays, there's a function for finding the rect of a tag editor somewhere, so it might work if I use that.

**Comment by MewPurPur** [comment]
Solved by #719
