### ISSUE TITLE
Add Ctrl+Q as a shortcut for closing on linux

### ISSUE THREAD

**Issue by WeaverSong** [MewPurPur/GodSVG#716]
Extremely minor qol. Ctrl+Q is a standard shortcut for closing applications on linux, and adding it would help streamline workflow for linux users.

**Comment by MewPurPur** [comment]
Approved, I'll add this right now.

**Comment by Kiisu-Master** [comment]
Doesn't need to be Linux only, it's used in many apps on any platform.

**Comment by MewPurPur** [comment]
Resolved by #717
