### ISSUE TITLE
Implement Web Support for Reference Images

### ISSUE THREAD

**Issue by Qainguin** [MewPurPur/GodSVG#752]
Add support for reference images for web import. Currently, it hides the reference image button for web users, which is more of a band-aid than anything.

**Comment by Qainguin** [comment]
I tried doing some work on this and I got to the point of where I could open the import native dialog but the problem was that loading it would not return a PackedByteArray with JavaScript but it would return a string.

**Comment by MewPurPur** [comment]
I don't know how to do this.

**Comment by Qainguin** [comment]
We might just have to shelve it for now, at least until someone knows how to.

**Comment by Kiisu-Master** [comment]
Ig this would be a task for me as i added svg opening on web

**Comment by Qainguin** [comment]
Ideally, a PR for this would also replace the JavaScriptBridge eval with get_interface to make it easier to read.
