### ISSUE TITLE
Color Picker eyedropper

### ISSUE THREAD

**Issue by MewPurPur** [MewPurPur/GodSVG#790]
Implementation in Godot should look something like:

1) Get viewport texture

2) Turn into image

3) Blit the image to the relevant part and upscale it with nearest filtering

4) Take center pixel as the color and draw graphics

Firefox has this implementation and it looks awesome:

![image](https://github.com/MewPurPur/GodSVG/assets/85438892/b33ceafc-57c1-402f-8da6-ce7aa93223cf)

**Comment by Swarkin** [comment]
Should this be display wide or only inside the application?

**Comment by MewPurPur** [comment]
I think it should only be inside the application, so that we could have this zoom thingy following the mouse. (it wouldn't work otherwise, would it?)

**Comment by Swarkin** [comment]
It's surely possible to spawn a new transparent window

**Comment by MewPurPur** [comment]
I guess, but in my opinion it's best to start off simple. Transparent windows feels like something that can open a can of worms. Even if it's strictly better, a fallback will probably still be needed.
