### ISSUE TITLE
Moving your mouse a little while clicking on the tag button makes it unpress.

### ISSUE THREAD

**Issue by MewPurPur** [MewPurPur/GodSVG#793]
![image](https://github.com/MewPurPur/GodSVG/assets/85438892/6ab9a37a-5383-42f8-ba41-dafc98103a10)

These buttons have the issue described in the title.

**Comment by Swarkin** [comment]
this is usually considered to be a feature, so that you can move away the mouse to cancel the clicking operation

however, most of the time you have to move the mouse away from the button's entire bounding box instead of just a single pixel

**Comment by MewPurPur** [comment]
Yes, exactly.
