### ISSUE TITLE
Grab handle for paths jitters between two positions with scaled UI

### ISSUE THREAD

**Issue by Dr-Doofus** [MewPurPur/GodSVG#927]
https://github.com/user-attachments/assets/317dc5fd-af9c-4ff3-b272-f65ded7e1bc4

Tested on v1.0-alpha5.

Attached video first shows sliding one of the path points at 1.5 UI scale. In this case, it jitters to the top left. Oddly enough, this is not the case for any other shape, only paths. UI scales below 1 show the exact same issue but it jitters in the other direction.
Dragging a path handle with one point makes the jittering effect easy to ignore, but for anything that makes a valid filling shape it becomes rather distracting.

Settings are left on default since updating, other than UI scale. I did use v1.0-alpha2 before.

Tested this on Linux Mint, but also the Windows version (via Wine) seems to have this issue as well.

**EDIT**: I'd also like to add that v1.0-alpha4 did not have this issue. Also forgot that the version I was using didn't have the new settings menu. Sorry about that.

**EDIT 2**: With brief testing, I tested the releases alpha3 and alpha4, and it turns out they did not have this issue. This bug was specifically introduced in alpha5.

**Comment by MewPurPur** [comment]
Thank you for the report!
